:bento: UNT-T24589: Add assets and fonts
ami-b-simform/podcasty pull request #1
Opened 2024-04-29 11:14 UTC by ami-b-simform

Contains assets and fonts for the app

2024-04-30 09:16 UTC, aditya-css requested changes

2024-04-30 09:16 UTC, aditya-css commented on .gitignore
Please configure your IDE to put a blank line at the end of the file.

2024-04-30 09:16 UTC, aditya-css commented on assets/images/arrow.png
Make sure to avoid any extra spaces while exporting an image.

2024-04-30 09:57 UTC, ami-b-simform commented on assets/images/arrow.png
comment resolved

2024-05-01 07:07 UTC, aditya-css approved these changes

2024-05-01 07:07 UTC, merged